<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <meta name="keywords" content="HTML5, CSS layout, web technology project, PHP, MySQL, Database, Apache, XAMPP">
  <meta name="author" content="Morgan Hopkins, Jonathon Taylor, Shaun Vambe">
  <title><?php echo $pageTitle; ?></title>
  
  <link rel="stylesheet" href="styles/style.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

<header>
  <div class="header-left">
    <img src="images/logo1.png" alt="JSM University Logo" class="header-logo">
    <h1><strong><?php echo $pageHeading; ?></strong></h1>
  </div>