<?php
// Checks whether a session has been started
if (session_status() == PHP_SESSION_NONE) {
    // Starts a session if none
    session_start();
}

// Check if the user is exactly admin and is the one logged in
if (!isset($_SESSION['username']) || $_SESSION['username'] !== 'Admin') {
    // If authorization fails(if user is not admin) the user is redirected to login page with an error
    header('Location: login.php?error=Access denied. Administrator privileges required.');
    exit;
}
// Includes settigs file
require_once "settings.php";
// Attempts to connect to the database
$conn = mysqli_connect($host, $user, $password, $database);
// Checks for any connection failure from the database
if (!$conn) {
    // If connection fails and error message is displayed
    echo "<p>Unable to connect to the database.</p>";
    exit;
}

// Messages developed by GenAI GPT5
if (
    isset($_SESSION['username']) &&
    $_SESSION['username'] === 'Admin' &&
    $_SERVER['REQUEST_METHOD'] === 'POST' &&
    isset($_POST['action']) && $_POST['action'] === 'delete_by_refno' // Check for dedicated delete action
) {
    // Get the Reference Number from the post data
    $refDelete = ($_POST['ref_delete'] ?? '');
    // Default message class developed by GENAI GPT5 
    $messageClass = 'error'; // Default message class

    if (!empty($refDelete)) {
        // A parameterised SQL statement to delete the EOI by RefNo
        $stmt = mysqli_prepare($conn, "DELETE FROM eoi WHERE RefNo=?");
        // Bind the RefNo parameter to the statement
        mysqli_stmt_bind_param($stmt, "s", $refDelete); 
        // Execute statement
        mysqli_stmt_execute($stmt);
        // Check if a row was affected (deleted)
        if (mysqli_stmt_affected_rows($stmt) > 0) {
            $_SESSION['message'] = "EOI with Reference Number **$refDelete** deleted successfully.";
            $messageClass = 'success';
        } else {
            $_SESSION['message'] = "Error: EOI with Reference Number **$refDelete** not found.";
        }
        // Close statement
        mysqli_stmt_close($stmt);
    } else {
         $_SESSION['message'] = "Error: Please provide a valid Reference Number for deletion.";
    }
    // Store the message class in session for styling after redirect
    $_SESSION['message_class'] = $messageClass;
    // Redirect back to the same page
    header("Location: " . $_SERVER['PHP_SELF']);
    exit;
}

// // Check for admin role, 'Admin' username, and a form submission (POST request)
// Messages developed by GenAI GPT5
if (
    isset($_SESSION['username']) &&
    $_SESSION['username'] === 'Admin' &&
    $_SERVER['REQUEST_METHOD'] === 'POST'
) {
    $id = isset($_POST['id']) ? (int)$_POST['id'] : 0;
    // Get the new status from the post data
    $status = $_POST['status'] ?? '';
    $messageClass = 'error'; // Default message class

    // Check if ID is valid (greater than 0) and the status is one of the 3 allowed values
    if ($id > 0 && in_array($status, ['New','Current','Final'], true)) {
        // A paramterised SQL statement to update the status
        $stmt = mysqli_prepare($conn, "UPDATE eoi SET status=? WHERE id=?");
        // Bind the status and ID parameters to the statement
        mysqli_stmt_bind_param($stmt, "si", $status, $id);
        // Execute statement
        mysqli_stmt_execute($stmt);

        // Check if a row was affected (updated)
        if (mysqli_stmt_affected_rows($stmt) > 0) {
            $_SESSION['message'] = "Status for EOI ID **$id** updated to **$status** successfully.";
            $messageClass = 'success';
        } else {
            $_SESSION['message'] = "Error: Status update failed for EOI ID **$id**.";
        }
        // Close statement
        mysqli_stmt_close($stmt);
    } else {
        $_SESSION['message'] = "Error: Invalid EOI ID or status provided.";
    }
    // Redirect back to the same page
    header("Location: " . $_SERVER['PHP_SELF']); // avoid re-submit on refresh
    exit;
}


// Messages box developed by GenAI GPT5
if (isset($_SESSION['message'])) {
    $class = $_SESSION['message_class'] ?? 'success';
    $displayMessage = str_replace('**','', $_SESSION['message']); 

    echo "<p class='message-box {$class}'>{$displayMessage}</p>";
    unset($_SESSION['message']);
    unset($_SESSION['message_class']);
}

$currentPage = 'manage';
$pageTitle = 'JSM Manage Page';
$pageDescription = 'Manage page for JSM website';
$pageHeading = 'Manage EOIs - HR Manager';

include 'header.inc';
include 'nav.inc';
?>

<!---Styles generated by GPT5-->
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f7f6;
        overflow-x: hidden; /* <---  PREVENT FULL-PAGE SCROLL */
        }
    .table-responsive {
        /* THIS PROPERTY enables horizontal sliding/scrolling */
        overflow-x: auto; 
        margin-top: 20px;
    }
    .eoi-table {
        /* width: 100% ensures it fills the container up to max-width */
        width: 100%; 
        /* min-width forces a scrollbar if the screen is smaller than this width */
        min-width: 1200px; 
        border-collapse: collapse;
        box-shadow: 0 2px 5px rgba(0,0,0,0.1);
    }
    .eoi-table th, .eoi-table td {
        border: 1px solid #ddd;
        padding: 12px 10px;
        text-align: left;
        font-size: 0.9em;
        /* white-space: nowrap keeps all cells on one line, enforcing the scroll */
        white-space: nowrap; 
    }
    .eoi-table th {
        background-color: #233260ff;
        color: #ffffffff;
        font-weight: bold;
        text-transform: uppercase;
    }
    .eoi-table tr:nth-child(even) {
        background-color: #f9f9f9;
    }
    .eoi-table tr:hover {
        background-color: #f0f8ff;
    }
    .status-form {
        align-items: center;
        gap: 5px;
    }
    select {
        padding: 6px;
        border: 1px solid #ccc;
        border-radius: 4px;
        min-width: 100px;
    }
    input[type="submit"] {
        background-color: #4CAF50;
        color: white;
        padding: 6px 12px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s;
    }
    input[type="submit"]:hover {
        background-color: #45a049;
    }
.delete-reference {
        border: 1px solid #f44336;
        padding: 15px;
        margin-bottom: 20px;
        background-color: #ffebee;
        border-radius: 5px;
        display: flex;
        gap: 10px;
        align-items: center;
    }
    .delete-reference label {
        font-weight: bold;
        color: #d32f2f;
    }
    .delete-reference input[type="text"] {
        padding: 8px;
        border: 1px solid #f44336;
        border-radius: 4px;
        min-width: 150px;
    }
    .delete-reference input[type="submit"] {
        background-color: #f44336;
        padding: 8px 15px;
    }
    .delete-reference input[type="submit"]:hover {
        background-color: #d32f2f;
    }
    .search {
        border: 1px solid #f44336;
        padding: 15px;
        margin-bottom: 20px;
        background-color: #ffebee;
        border-radius: 5px;
        display: flex;
        gap: 10px;
        align-items: center;
    }
    .search label {
        font-weight: bold;
        color: #d32f2f;
    }
    .search input[type="text"] {
        padding: 8px;
        border: 1px solid #f44336;
        border-radius: 4px;
        min-width: 150px;
    }
    .search input[type="submit"] {
        background-color: #f44336;
        padding: 8px 15px;
    }
    .search input[type="submit"]:hover {
        background-color: #d32f2f;
    }
    #message-box {
        padding: 10px;
        margin-bottom: 15px;
        border-radius: 4px;
    }
    .success {
        background-color: #d4edda;
        color: #155724;
        border: 1px solid #c3e6cb;
    }
    .error {
        background-color: #f8d7da;
        color: #721c24;
        border: 1px solid #f5c6cb;
    }
    .search {
    border: 1px solid #1976d2;
    padding: 15px;
    margin-bottom: 20px;
    background-color: #e3f2fd;
    border-radius: 5px;
    display: flex;
    flex-wrap: wrap; 
    gap: 15px;
    align-items: center;
}
.search label {
    font-weight: bold;
    color: #233260ff;
    margin-right: 5px; 
}
.search input[type="text"] {
    padding: 8px 12px;
    border: 1px solid #1976d2;
    border-radius: 4px;
    min-width: 150px;
    flex-grow: 1;
    max-width: 250px;
    transition: border-color 0.3s, box-shadow 0.3s;
}
.search input[type="text"]:focus {
    border-color: #4CAF50;
    box-shadow: 0 0 5px rgba(76, 175, 80, 0.5);
    outline: none;
}
.search button[type="submit"] {

    background-color: #1976d2;
    color: white;
    padding: 8px 15px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s, transform 0.1s;
    font-weight: bold;
}
.search button[type="submit"]:hover {
    background-color: #1565c0;
    transform: translateY(-1px);
}
</style>
<div class="content-area">
    <header style="display:flex; justify-content:space-between; align-items:center; background:#1976d2; color:white; padding:1em;">
        <h2 style="margin:0;">Welcome, <?php echo htmlspecialchars($_SESSION['name']); ?></h2>
    </header>
    <div style="padding-bottom: 20px;">
    <h3><?php echo $pageHeading; ?></h3>
    <p>This panel is for administrators to view and manage all Expressions of Interest (EOIs).</p>
    </div>
<div class="delete-reference">
    <form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']); ?>" 
          onsubmit="return confirm('WARNING: This action is permanent. Are you absolutely sure you want to delete the EOI with the entered Reference Number?');">
        <label for="refno_input">Delete EOI by Reference Number:</label>
        <input type="text" id="refno_input" name="ref_delete" placeholder="e.g., JSM001" required> 
        <input type="hidden" name="action" value="delete_by_refno"> 
        <input type="submit" value="Delete EOI">
    </form>
</div>
<div class="search">
    <form method="GET" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']); ?>" >
        <label for="firstname_search">First Name Search:</label>
        <input type="text" id="firstname_search" name="search_firstname" 
        value="<?php echo isset($_GET['search_firstname']) ? htmlspecialchars($_GET['search_lastname']) : ''; ?>" placeholder="e.g., John">

        <label for="lastname_search">Last Name Search:</label>
        <input type="text" id="lastname_search" name="search_lastname" 
        value="<?php echo isset($_GET['search_lastname']) ? htmlspecialchars($_GET['search_firstname']) : ''; ?>" placeholder="e.g., Doe">

        <button type="submit" class="btn btn-primary">Search</button>
    </form>
</div>
<div class="Sort">
        <label for="sort_field">Sort By:</label>
        <select name="sort_field" id="sort_field">
            <option value="RefNo" <?php 
                if ($sortField == 'RefNo') echo 'selected'; ?>>EOI Reference
            </option>
            <option value="LastName" <?php 
                if ($sortField == 'LastName') echo 'selected'; ?>>Applicant Last Name
            </option>
            <option value="Status" <?php 
                if ($sortField == 'Status') echo 'selected'; ?>>status
            </option>
        </select>
        <button type="submit" class="btn btn-primary">Sort</button>
</div>

<?php

$search_performed = false;
$get_name = [];

// Check if a first name search term is provided in the GET request
if (!empty($_GET['search_firstname'])) {
    $FirstName = mysqli_real_escape_string($conn, $_GET['search_firstname']);
    $get_name[] = "FirstName LIKE '%$FirstName%'";
    $search_performed = true;
}

if (!empty($_GET['search_lastname'])) {
    $LastName = mysqli_real_escape_string($conn, $_GET['search_lastname']);
    $get_name[] = "LastName LIKE '%$LastName%'";
    $search_performed = true;
}

$query = "SELECT * FROM eoi";

if ($search_performed){
    $query .= " WHERE " . implode(" AND ", $get_name);
}
// SQL query to select all data from the 'eoi' table, ordered by Reference Number
$query .= " ORDER BY RefNo";
// Store in result and executes the query
$result = mysqli_query($conn, $query);

// Checks if the query execution failed
if (!$result) {
    // If query fauled, error is displayed
    echo "<p>Error in query: " . mysqli_error($conn) . "</p>";
}

// Checks if query was successful and atleast returned one row of data 
if ($result && mysqli_num_rows($result) > 0) {
        // Table Responsive class
        echo "<div class='table-responsive'>";
        // EOI table class
        echo "<table class='eoi-table'>";
        // Table header row with its column names
        echo "<tr><th>RefNo</th><th>ID</th><th>ApplyDate</th><th>FirstName</th><th>LastName</th><th>DOB</th><th>Gender</th><th>Address</th><th>Suburb</th><th>Email</th><th>Phone.No</th><th>Skills</th><th>Other Skills</th><th>Status</th></tr>";
        // Loop each row of the query result
        while ($row = mysqli_fetch_assoc($result)) {
            echo "<tr>";
            echo "<td>" . htmlspecialchars($row['RefNo']) . "</td>";
            echo "<td>" . htmlspecialchars($row['ID']) . "</td>";
            echo "<td>" . htmlspecialchars($row['ApplyDate']) . "</td>";
            echo "<td>" . htmlspecialchars($row['FirstName']) . "</td>";
            echo "<td>" . htmlspecialchars($row['LastName']) . "</td>";
            echo "<td>" . htmlspecialchars($row['DOB']) . "</td>";
            echo "<td>" . htmlspecialchars($row['Gender']) . "</td>";
            echo "<td>" . htmlspecialchars($row['Address']) . "</td>";
            echo "<td>" . htmlspecialchars($row['Suburb']) . "</td>";
            echo "<td>" . htmlspecialchars($row['Email']) . "</td>";
            echo "<td>" . htmlspecialchars($row['PhoneNo']) . "</td>";
            echo "<td>" . htmlspecialchars($row['Skills']) . "</td>";
            echo "<td>" . htmlspecialchars($row['OtherSkills']) . "</td>";
            // Start of the table data for EOI status
            echo "<td>";
            // Get the current status for the row
            $currentStatus = htmlspecialchars($row['Status'] ?? '');
            // Form for status update (using post to the current page)
            echo '<form method="post" action="' . htmlspecialchars($_SERVER['PHP_SELF']). '" class="status-form" style="display: inline-flex;">';
            // Pass the EOI ID to the post request
            echo '<input type="hidden" name="id" value="' . (int)$row['ID'] . '">';
            // Status selelction dropdown menu
            echo '<select name="status">';
            // Option for New, selected if it matches the current status
            echo '<option value="New"' . ($currentStatus == 'New' ? ' selected' : '') . '>New</option>';
            // Option for Current, selected if it matches the current status
            echo '<option value="Current"' . ($currentStatus == 'Current' ? ' selected' : '') . '>Current</option>';
            // Option for New, selected if it matches the current status
            echo '<option value="Final"' . ($currentStatus == 'Final' ? ' selected' : '') . '>Final</option>';
            // Select tag closed
            echo '</select>';
            // Button to save the new status
            echo '<input type="submit" value="Save">';
            // Form tag closed
            echo '</form>';
            // Status table data tag closed
            echo "</td>";
            // Table row closed
            echo "</tr>";
        }
    echo "</table>";
} else {
    //if there are no EOIs found in the table
    echo "<p>There are no EOIs to display.</p>";
}
// If the query was successful (returned the list of data)
if ($result) {
    // Comoputer memory free up that was used to hold the list of EOIs
    mysqli_free_result($result);
}
// Close the datatbase connection
mysqli_close($conn);
?>
</div>
<?php include 'footer.inc'; ?>