<?php
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}

// Check if admin is logged in
if (!isset($_SESSION['username']) || $_SESSION['username'] !== 'Admin') {
    header('Location: login.php?error=Access denied. Administrator privileges required.');
    exit;
}

$currentPage = 'manage';
$pageTitle = 'JSM Manage Page';
$pageDescription = 'Manage page for JSM website';
$pageHeading = 'Manage EOIs - HR Manager';

include 'header.inc';
include 'nav.inc';
?>

<!---Styles generated by GPT5-->
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f7f6;
        overflow-x: hidden; /* <---  PREVENT FULL-PAGE SCROLL */
        }
    .table-responsive {
        /* THIS PROPERTY enables horizontal sliding/scrolling */
        overflow-x: auto; 
        margin-top: 20px;
    }
    .eoi-table {
        /* width: 100% ensures it fills the container up to max-width */
        width: 100%; 
        /* min-width forces a scrollbar if the screen is smaller than this width */
        min-width: 1200px; 
        border-collapse: collapse;
        box-shadow: 0 2px 5px rgba(0,0,0,0.1);
    }
    .eoi-table th, .eoi-table td {
        border: 1px solid #ddd;
        padding: 12px 10px;
        text-align: left;
        font-size: 0.9em;
        /* white-space: nowrap keeps all cells on one line, enforcing the scroll */
        white-space: nowrap; 
    }
    .eoi-table th {
        background-color: #233260ff;
        color: #ffffffff;
        font-weight: bold;
        text-transform: uppercase;
    }
    .eoi-table tr:nth-child(even) {
        background-color: #f9f9f9;
    }
    .eoi-table tr:hover {
        background-color: #f0f8ff;
    }
    .status-form {
        align-items: center;
        gap: 5px;
    }
    select {
        padding: 6px;
        border: 1px solid #ccc;
        border-radius: 4px;
        min-width: 100px;
    }
    input[type="submit"] {
        background-color: #4CAF50;
        color: white;
        padding: 6px 12px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s;
    }
    input[type="submit"]:hover {
        background-color: #45a049;
    }
</style>
<div class="content-area">
    <header style="display:flex; justify-content:space-between; align-items:center; background:#1976d2; color:white; padding:1em;">
        <h2 style="margin:0;">Welcome, <?php echo htmlspecialchars($_SESSION['name']); ?></h2>
    </header>
    <div style="padding-bottom: 20px;">
    <h3><?php echo $pageHeading; ?></h3>
    <p>This panel is for administrators to view and manage all Expressions of Interest (EOIs).</p>
    </div>
<?php
require_once "settings.php";
$conn = mysqli_connect($host, $user, $password, $database);
if (!$conn) {
    echo "<p>Unable to connect to the database.</p>";
    exit;
}
if (
    isset($_SESSION['username']) &&
    $_SESSION['username'] === 'Admin' &&
    $_SERVER['REQUEST_METHOD'] === 'POST'
) {
    $id = isset($_POST['id']) ? (int)$_POST['id'] : 0;
    $status = $_POST['status'] ?? '';
    if ($id > 0 && in_array($status, ['New','Current','Final'], true)) {
        $stmt = mysqli_prepare($conn, "UPDATE eoi SET status=? WHERE id=?");
        mysqli_stmt_bind_param($stmt, "si", $status, $id);
        mysqli_stmt_execute($stmt);
        mysqli_stmt_close($stmt);
    }
    header("Location: " . $_SERVER['PHP_SELF']); // avoid re-submit on refresh
    exit;
}
$query = "SELECT * FROM eoi ORDER BY RefNo";
$result = mysqli_query($conn, $query);
if (!$result) {
    echo "<p>Error in query: " . mysqli_error($conn) . "</p>";
}
if ($result && mysqli_num_rows($result) > 0) {
        echo "<div class='table-responsive'>";
        echo "<table class='eoi-table'>";
        echo "<tr><th>RefNo</th><th>ID</th><th>ApplyDate</th><th>FirstName</th><th>LastName</th><th>DOB</th><th>Gender</th><th>Address</th><th>Suburb</th><th>Email</th><th>Phone.No</th><th>Skills</th><th>Other Skills</th><th>Status</th></tr>";
        while ($row = mysqli_fetch_assoc($result)) {
            echo "<tr>";
            echo "<td>" . htmlspecialchars($row['RefNo']) . "</td>";
            echo "<td>" . htmlspecialchars($row['ID']) . "</td>";
            echo "<td>" . htmlspecialchars($row['ApplyDate']) . "</td>";
            echo "<td>" . htmlspecialchars($row['FirstName']) . "</td>";
            echo "<td>" . htmlspecialchars($row['LastName']) . "</td>";
            echo "<td>" . htmlspecialchars($row['DOB']) . "</td>";
            echo "<td>" . htmlspecialchars($row['Gender']) . "</td>";
            echo "<td>" . htmlspecialchars($row['Address']) . "</td>";
            echo "<td>" . htmlspecialchars($row['Suburb']) . "</td>";
            echo "<td>" . htmlspecialchars($row['Email']) . "</td>";
            echo "<td>" . htmlspecialchars($row['PhoneNo']) . "</td>";
            echo "<td>" . htmlspecialchars($row['Skills']) . "</td>";
            echo "<td>" . htmlspecialchars($row['OtherSkills']) . "</td>";
            echo "<td>";
            $currentStatus = htmlspecialchars($row['Status'] ?? '');
            echo '<form method="post" action="' . htmlspecialchars($_SERVER['PHP_SELF']). '" class="status-form" style="display: inline-flex;">';
            echo '<input type="hidden" name="id" value="' . (int)$row['ID'] . '">';
            echo '<select name="status">';
            echo '<option value="New"' . ($currentStatus == 'New' ? ' selected' : '') . '>New</option>';
            echo '<option value="Current"' . ($currentStatus == 'Current' ? ' selected' : '') . '>Current</option>';
            echo '<option value="Final"' . ($currentStatus == 'Final' ? ' selected' : '') . '>Final</option>';
            echo '</select>';
            echo '<input type="submit" value="Save">';
            echo '</form>';
            echo "</td>";
            echo "</tr>";
        }
    echo "</table>";
} else {
    //if there are no EOIs found in the table
    echo "<p>There are no EOIs to display.</p>";
}
if ($result) {
    mysqli_free_result($result);
}
mysqli_close($conn);
?>
</div>
<?php include 'footer.inc'; ?>